[versions]
agp = "8.5.2"
kotlin = "2.0.20"
coreKtx = "1.13.1"
appcompat = "1.7.0"
wearable = "2.9.0"
playServicesWearable = "18.1.0"
androidxWear = "1.3.0"
recyclerview = "1.3.2"
lifecycle = "2.8.4"
coroutines = "1.8.1"
guava = "33.2.1-android"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-wear = { group = "androidx.wear", name = "wear", version.ref = "androidxWear" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }
wearable = { group = "com.google.android.support", name = "wearable", version.ref = "wearable" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
